# Generated by Django 3.2.10 on 2023-10-11 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=256)),
                ('EventDescription', models.CharField(max_length=256)),
                ('EventLocation', models.CharField(max_length=256)),
                ('EventCategory', multiselectfield.db.fields.MultiSelectField(choices=[('Reading', 'Reading'), ('Cycling', 'Cycling'), ('Hiking', 'Hiking'), ('Drawing', 'Drawing'), ('Photography', 'Photography'), ('Swimming', 'Swimming'), ('Sleeping', 'Sleeping'), ('Sports', 'Sports'), ('Gaming', 'Gaming')], max_length=26)),
                ('EventStartTime', models.DateTimeField(null=True)),
                ('EventParticipants', django_mysql.models.ListTextField(models.IntegerField(), default=0, null=True, size=50)),
                ('EventCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
